[tool.poetry]
name = "wrath_and_glory_xp_optimizer"
version = "2.0.0"
description = "A tool to optimize the spent xp on a character for the Wrath & Glory RPG."
authors = ["D. J. Mack <dj_mack@gmx.de>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/LordFckHelmchen/WrathAndGloryXPOptimizer"
keywords = ["rpg", "rpg-tool",  "wrathandglory", "optimization", "mixed-integer non-linear programming", "minlp", "gekko"]
repository = "https://github.com/LordFckHelmchen/WrathAndGloryXPOptimizer"

[tool.poetry.dependencies]
python = "^3.8"
gekko = "^0.2.8"
numpy = "^1.20.2"
click = "^7.1.2"
Flask = "^1.1.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.3"
coverage = {extras = ["toml"], version = "^5.5"}
pytest-cov = "^2.11.1"

[tool.poetry.scripts]
optimize-xp = "wrath_and_glory_xp_optimizer.optimize_xp:cli"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["wrath_and_glory_xp_optimizer"]

[tool.coverage.report]
show_missing = true
fail_under = 100

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
